---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cilium
  - external-secrets
  - kube-state-metrics
  - metrics-server
  - node-exporter
  - tetragon
  - traefik
