apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technitium-key
  namespace: technitium
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: technitium-api-key
    template:
      type: Opaque
      data:
        api-key: "{{.api_token}}"
  data:
    - secretKey: api_token
      remoteRef:
        key: technitium/metrics-token
        property: api-token
