---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications.yaml
  - configuration.yaml
  - flux-sync.yaml
  - infrastructure.yaml
  - _cluster-overrides/cilium-cluster-values.yaml
  - _cluster-overrides/traefik-cluster-values.yaml
  - _cluster-overrides/cluster-substitutions.yaml
