---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - applications.yaml
  - configuration.yaml
  - flux-sync.yaml
  - infrastructure.yaml
  - _cluster-overrides/cilium-cluster-values.yaml
  - _cluster-overrides/traefik-cluster-values.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: cluster-substitutions
    namespace: flux-system
    literals:
      - cluster=tres-sims-com
  - name: traefik-cluster-values
    namespace: traefik
    options:
      labels:
        reconcile.fluxcd.io/watch: Enabled
    files:
      - values.yaml=_cluster-overrides/traefik-cluster-values.yaml
