---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications.yaml
  - configuration.yaml
  - flux-sync.yaml
  - infrastructure.yaml
generatorOptions:
  disableNameSufficHash: true
configMapGenerator:
  - name: cluster-substitutions
    literals:
      - cluster=tres-sims
  - name: cilium-cluster-values
    options:
      labels:
        reconcile.fluxcd.io/watch: Enabled
    files:
      - values.yaml=_cluster-overrides/cilium-cluster-values.yaml
  - name: traefik-cluster-values
    options:
      labels:
        reconcile.fluxcd.io/watch: Enabled
    files:
      - values.yaml=_cluster-overrides/traefik-cluster-values.yaml
