---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: "./base/infrastructure"
  prune: true
  timeout: 1m
  dependsOn:
    - name: flux-system
  components:
    - "./base/infrastructure/_components/csi/nfs-csi"
    - "./base/infrastructure/_components/metallb"
