---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications.yaml
  - configuration.yaml
  - flux-sync.yaml
  - infrastructure.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: cluster-substitutions
    namespace: flux-system
    literals:
      - cluster=deep-thonk
  - name: cilium-cluster-values
    namespace: kube-system
    options:
      labels:
        reconcile.fluxcd.io/watch: Enabled
    files:
      - values.yaml=_cluster-overrides/cilium-cluster-values.yaml
  - name: csi-driver-nfs-cluster-values
    namepsace: nfs-csi
    options:
      labels:
        reconcile.fluxcd.io/watch: Enabled
    files:
      - values.yaml=_cluster-overrides/csi-driver-nfs-cluster-values.yaml
