---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: flux-system
resources:
  - applications.yaml
  - configuration.yaml
  - flux-sync.yaml
  - infrastructure.yaml
  - _cluster-overrides/cilium-cluster-values.yaml
  - _cluster-overrides/csi-driver-nfs-cluster-values.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: cluster-substitutions
    literals:
      - cluster=deep-thonk
