---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: jellyfin-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-tv
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: jellyfin-tv
