---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 10m
  chart:
    spec:
      chart: jellyfin
      version: "3.2.0"
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: jellyfin
      interval: 10m
  values:
    ingress:
      enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - jellyfin.k8s.deep-thonk.com
        secretName: jellyfin.tls
    volumes:
      - name: jellyfin-movies
        persistentVolumeClaim:
          claimName: jellyfin-movies
      - name: jellyfin-tv
        persistentVolumeClaim:
          claimName: jellyfin-tv
    volumeMounts:
      - name: jellyfin-movies
        mountPath: /mnt/jellyin-movies
      - name: jellyfin-tv
        mountPath: /mnt/jellyin-tv
    persistence:
      media:
        enabled: false
    metrics:
      enabled: true
